version: '3.9'
services:
  postgres:
    image: postgres:14-bullseye
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=client
    ports:
      - "5432:5432"


  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DB_SOURCE=postgresql://root:postgres@postgres:5432/client?sslmode=disable    
    depends_on:
      - postgres
    entrypoint: ["/app/wait-for.sh","postgres:5432","--","/app/start.sh"]
    command: [ "/app/main" ]