// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"database/sql"
)

type Client struct {
	ID          int64        `json:"id"`
	FirstName   string       `json:"first_name"`
	SecondName  string       `json:"second_name"`
	Email       string       `json:"email"`
	PhoneNumber int32        `json:"phone_number"`
	Language    string       `json:"language"`
	Time        interface{}  `json:"time"`
	UpdatedAt   sql.NullTime `json:"updated_at"`
	CreatedAt   sql.NullTime `json:"created_at"`
}
