// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: profile.sql

package db

import (
	"context"
)

const createProfile = `-- name: CreateProfile :one
INSERT INTO profile (
  id,
  name,
  gender,
  email,
  phone_number,
  address_line,
  country,
  native_language
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8)
RETURNING id, name, gender, phone_number, email, address_line, country, native_language
`

type CreateProfileParams struct {
	ID             int64  `json:"id"`
	Name           string `json:"name"`
	Gender         string `json:"gender"`
	Email          string `json:"email"`
	PhoneNumber    string `json:"phone_number"`
	AddressLine    string `json:"address_line"`
	Country        string `json:"country"`
	NativeLanguage string `json:"native_language"`
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) (Profile, error) {
	row := q.db.QueryRowContext(ctx, createProfile,
		arg.ID,
		arg.Name,
		arg.Gender,
		arg.Email,
		arg.PhoneNumber,
		arg.AddressLine,
		arg.Country,
		arg.NativeLanguage,
	)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Gender,
		&i.PhoneNumber,
		&i.Email,
		&i.AddressLine,
		&i.Country,
		&i.NativeLanguage,
	)
	return i, err
}
