apiVersion: v1
kind: ConfigMap
metadata: 
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::190661032801:user/githubclient-ci  
      username: githubclient-ci
      groups: 
        - system:masters