apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-api-deployment
  labels:
    app: client-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-api
  template:
    metadata:
      labels:
        app: client-api
    spec:
      containers:
      - name: client-api
        image: 190661032801.dkr.ecr.us-east-1.amazonaws.com/client:b0999dc3b40e6cdf7cc32aea50fa40e961119116
        ports:
        - containerPort: 8000