name: yioko

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]


jobs:
  test: 
    name: Test
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgres:11-alpine
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: client
        ports:
          - "8001:5432"
        options: 
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    
  